---
- job:
    name: openstack-project-manager-mypy
    parent: mypy
    pre-run: playbooks/mypy.yml

- job:
    name: openstack-project-manager-tox
    parent: tox
    pre-run: playbooks/tox.yml
    vars:
      tox_envlist: test

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8
        - openstack-project-manager-mypy
        - openstack-project-manager-tox
        - yamllint
        - python-black

    gate:
      jobs:
        - flake8
        - openstack-project-manager-mypy
        - openstack-project-manager-tox
        - yamllint
        - python-black

    periodic-daily:
      jobs:
        - flake8
        - openstack-project-manager-mypy
        - openstack-project-manager-tox
        - yamllint
        - python-black
